/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as EmailHelpRouteImport } from './routes/email-help'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiConceptImageRouteImport } from './routes/api/concept-image'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSepticRouteImport } from './routes/_authenticated/septic'
import { Route as AuthenticatedSchemaDiffRouteImport } from './routes/_authenticated/schema-diff'
import { Route as AuthenticatedProposalsRouteImport } from './routes/_authenticated/proposals'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedKnowledgeBaseRouteImport } from './routes/_authenticated/knowledge-base'
import { Route as AuthenticatedJobManagementRouteImport } from './routes/_authenticated/job-management'
import { Route as AuthenticatedJobCostingRouteImport } from './routes/_authenticated/job-costing'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedHomeBuilderRouteImport } from './routes/_authenticated/home-builder'
import { Route as AuthenticatedHistoricRouteImport } from './routes/_authenticated/historic'
import { Route as AuthenticatedFieldCaptureRouteImport } from './routes/_authenticated/field-capture'
import { Route as AuthenticatedEstimatesRouteImport } from './routes/_authenticated/estimates'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContainerBuildsRouteImport } from './routes/_authenticated/container-builds'
import { Route as AuthenticatedConceptStudioRouteImport } from './routes/_authenticated/concept-studio'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as PortalProposalTokenRouteImport } from './routes/portal.proposal.$token'
import { Route as PortalInvoiceTokenRouteImport } from './routes/portal.invoice.$token'
import { Route as PortalClientFileTokenRouteImport } from './routes/portal.client-file.$token'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedFieldCaptureProjectIdRouteImport } from './routes/_authenticated/field-capture.$projectId'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminGitSyncRouteImport } from './routes/_authenticated/admin.git-sync'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiProposalsIdPdfRouteImport } from './routes/api/proposals.$id.pdf'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailHelpRoute = EmailHelpRouteImport.update({
  id: '/email-help',
  path: '/email-help',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConceptImageRoute = ApiConceptImageRouteImport.update({
  id: '/api/concept-image',
  path: '/api/concept-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSepticRoute = AuthenticatedSepticRouteImport.update({
  id: '/septic',
  path: '/septic',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchemaDiffRoute = AuthenticatedSchemaDiffRouteImport.update({
  id: '/schema-diff',
  path: '/schema-diff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProposalsRoute = AuthenticatedProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeBaseRoute =
  AuthenticatedKnowledgeBaseRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobManagementRoute =
  AuthenticatedJobManagementRouteImport.update({
    id: '/job-management',
    path: '/job-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobCostingRoute = AuthenticatedJobCostingRouteImport.update({
  id: '/job-costing',
  path: '/job-costing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeBuilderRoute =
  AuthenticatedHomeBuilderRouteImport.update({
    id: '/home-builder',
    path: '/home-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricRoute = AuthenticatedHistoricRouteImport.update({
  id: '/historic',
  path: '/historic',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFieldCaptureRoute =
  AuthenticatedFieldCaptureRouteImport.update({
    id: '/field-capture',
    path: '/field-capture',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstimatesRoute = AuthenticatedEstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContainerBuildsRoute =
  AuthenticatedContainerBuildsRouteImport.update({
    id: '/container-builds',
    path: '/container-builds',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConceptStudioRoute =
  AuthenticatedConceptStudioRouteImport.update({
    id: '/concept-studio',
    path: '/concept-studio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalProposalTokenRoute = PortalProposalTokenRouteImport.update({
  id: '/portal/proposal/$token',
  path: '/portal/proposal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalInvoiceTokenRoute = PortalInvoiceTokenRouteImport.update({
  id: '/portal/invoice/$token',
  path: '/portal/invoice/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalClientFileTokenRoute = PortalClientFileTokenRouteImport.update({
  id: '/portal/client-file/$token',
  path: '/portal/client-file/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProjectsRoute,
} as any)
const AuthenticatedFieldCaptureProjectIdRoute =
  AuthenticatedFieldCaptureProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedFieldCaptureRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminGitSyncRoute =
  AuthenticatedAdminGitSyncRouteImport.update({
    id: '/admin/git-sync',
    path: '/admin/git-sync',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProposalsIdPdfRoute = ApiProposalsIdPdfRouteImport.update({
  id: '/api/proposals/$id/pdf',
  path: '/api/proposals/$id/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/email-help': typeof EmailHelpRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/concept-studio': typeof AuthenticatedConceptStudioRoute
  '/container-builds': typeof AuthenticatedContainerBuildsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/field-capture': typeof AuthenticatedFieldCaptureRouteWithChildren
  '/historic': typeof AuthenticatedHistoricRoute
  '/home-builder': typeof AuthenticatedHomeBuilderRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/job-costing': typeof AuthenticatedJobCostingRoute
  '/job-management': typeof AuthenticatedJobManagementRoute
  '/knowledge-base': typeof AuthenticatedKnowledgeBaseRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/proposals': typeof AuthenticatedProposalsRoute
  '/schema-diff': typeof AuthenticatedSchemaDiffRoute
  '/septic': typeof AuthenticatedSepticRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/api/concept-image': typeof ApiConceptImageRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/git-sync': typeof AuthenticatedAdminGitSyncRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/field-capture/$projectId': typeof AuthenticatedFieldCaptureProjectIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/portal/client-file/$token': typeof PortalClientFileTokenRoute
  '/portal/invoice/$token': typeof PortalInvoiceTokenRoute
  '/portal/proposal/$token': typeof PortalProposalTokenRoute
  '/api/proposals/$id/pdf': typeof ApiProposalsIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/email-help': typeof EmailHelpRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/concept-studio': typeof AuthenticatedConceptStudioRoute
  '/container-builds': typeof AuthenticatedContainerBuildsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/field-capture': typeof AuthenticatedFieldCaptureRouteWithChildren
  '/historic': typeof AuthenticatedHistoricRoute
  '/home-builder': typeof AuthenticatedHomeBuilderRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/job-costing': typeof AuthenticatedJobCostingRoute
  '/job-management': typeof AuthenticatedJobManagementRoute
  '/knowledge-base': typeof AuthenticatedKnowledgeBaseRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/proposals': typeof AuthenticatedProposalsRoute
  '/schema-diff': typeof AuthenticatedSchemaDiffRoute
  '/septic': typeof AuthenticatedSepticRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/api/concept-image': typeof ApiConceptImageRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/git-sync': typeof AuthenticatedAdminGitSyncRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/field-capture/$projectId': typeof AuthenticatedFieldCaptureProjectIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/portal/client-file/$token': typeof PortalClientFileTokenRoute
  '/portal/invoice/$token': typeof PortalInvoiceTokenRoute
  '/portal/proposal/$token': typeof PortalProposalTokenRoute
  '/api/proposals/$id/pdf': typeof ApiProposalsIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/email-help': typeof EmailHelpRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/concept-studio': typeof AuthenticatedConceptStudioRoute
  '/_authenticated/container-builds': typeof AuthenticatedContainerBuildsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/estimates': typeof AuthenticatedEstimatesRoute
  '/_authenticated/field-capture': typeof AuthenticatedFieldCaptureRouteWithChildren
  '/_authenticated/historic': typeof AuthenticatedHistoricRoute
  '/_authenticated/home-builder': typeof AuthenticatedHomeBuilderRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/job-costing': typeof AuthenticatedJobCostingRoute
  '/_authenticated/job-management': typeof AuthenticatedJobManagementRoute
  '/_authenticated/knowledge-base': typeof AuthenticatedKnowledgeBaseRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/proposals': typeof AuthenticatedProposalsRoute
  '/_authenticated/schema-diff': typeof AuthenticatedSchemaDiffRoute
  '/_authenticated/septic': typeof AuthenticatedSepticRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/api/concept-image': typeof ApiConceptImageRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/git-sync': typeof AuthenticatedAdminGitSyncRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/field-capture/$projectId': typeof AuthenticatedFieldCaptureProjectIdRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/portal/client-file/$token': typeof PortalClientFileTokenRoute
  '/portal/invoice/$token': typeof PortalInvoiceTokenRoute
  '/portal/proposal/$token': typeof PortalProposalTokenRoute
  '/api/proposals/$id/pdf': typeof ApiProposalsIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/email-help'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/clients'
    | '/concept-studio'
    | '/container-builds'
    | '/dashboard'
    | '/estimates'
    | '/field-capture'
    | '/historic'
    | '/home-builder'
    | '/invoices'
    | '/job-costing'
    | '/job-management'
    | '/knowledge-base'
    | '/leads'
    | '/payments'
    | '/pricing'
    | '/projects'
    | '/proposals'
    | '/schema-diff'
    | '/septic'
    | '/settings'
    | '/team'
    | '/api/concept-image'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/git-sync'
    | '/admin/logs'
    | '/clients/$id'
    | '/field-capture/$projectId'
    | '/projects/$id'
    | '/portal/client-file/$token'
    | '/portal/invoice/$token'
    | '/portal/proposal/$token'
    | '/api/proposals/$id/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/email-help'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/clients'
    | '/concept-studio'
    | '/container-builds'
    | '/dashboard'
    | '/estimates'
    | '/field-capture'
    | '/historic'
    | '/home-builder'
    | '/invoices'
    | '/job-costing'
    | '/job-management'
    | '/knowledge-base'
    | '/leads'
    | '/payments'
    | '/pricing'
    | '/projects'
    | '/proposals'
    | '/schema-diff'
    | '/septic'
    | '/settings'
    | '/team'
    | '/api/concept-image'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/git-sync'
    | '/admin/logs'
    | '/clients/$id'
    | '/field-capture/$projectId'
    | '/projects/$id'
    | '/portal/client-file/$token'
    | '/portal/invoice/$token'
    | '/portal/proposal/$token'
    | '/api/proposals/$id/pdf'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/email-help'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/clients'
    | '/_authenticated/concept-studio'
    | '/_authenticated/container-builds'
    | '/_authenticated/dashboard'
    | '/_authenticated/estimates'
    | '/_authenticated/field-capture'
    | '/_authenticated/historic'
    | '/_authenticated/home-builder'
    | '/_authenticated/invoices'
    | '/_authenticated/job-costing'
    | '/_authenticated/job-management'
    | '/_authenticated/knowledge-base'
    | '/_authenticated/leads'
    | '/_authenticated/payments'
    | '/_authenticated/pricing'
    | '/_authenticated/projects'
    | '/_authenticated/proposals'
    | '/_authenticated/schema-diff'
    | '/_authenticated/septic'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/api/concept-image'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/git-sync'
    | '/_authenticated/admin/logs'
    | '/_authenticated/clients/$id'
    | '/_authenticated/field-capture/$projectId'
    | '/_authenticated/projects/$id'
    | '/portal/client-file/$token'
    | '/portal/invoice/$token'
    | '/portal/proposal/$token'
    | '/api/proposals/$id/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EmailHelpRoute: typeof EmailHelpRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiConceptImageRoute: typeof ApiConceptImageRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  PortalClientFileTokenRoute: typeof PortalClientFileTokenRoute
  PortalInvoiceTokenRoute: typeof PortalInvoiceTokenRoute
  PortalProposalTokenRoute: typeof PortalProposalTokenRoute
  ApiProposalsIdPdfRoute: typeof ApiProposalsIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-help': {
      id: '/email-help'
      path: '/email-help'
      fullPath: '/email-help'
      preLoaderRoute: typeof EmailHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/concept-image': {
      id: '/api/concept-image'
      path: '/api/concept-image'
      fullPath: '/api/concept-image'
      preLoaderRoute: typeof ApiConceptImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/septic': {
      id: '/_authenticated/septic'
      path: '/septic'
      fullPath: '/septic'
      preLoaderRoute: typeof AuthenticatedSepticRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schema-diff': {
      id: '/_authenticated/schema-diff'
      path: '/schema-diff'
      fullPath: '/schema-diff'
      preLoaderRoute: typeof AuthenticatedSchemaDiffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals': {
      id: '/_authenticated/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AuthenticatedProposalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge-base': {
      id: '/_authenticated/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AuthenticatedKnowledgeBaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/job-management': {
      id: '/_authenticated/job-management'
      path: '/job-management'
      fullPath: '/job-management'
      preLoaderRoute: typeof AuthenticatedJobManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/job-costing': {
      id: '/_authenticated/job-costing'
      path: '/job-costing'
      fullPath: '/job-costing'
      preLoaderRoute: typeof AuthenticatedJobCostingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home-builder': {
      id: '/_authenticated/home-builder'
      path: '/home-builder'
      fullPath: '/home-builder'
      preLoaderRoute: typeof AuthenticatedHomeBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historic': {
      id: '/_authenticated/historic'
      path: '/historic'
      fullPath: '/historic'
      preLoaderRoute: typeof AuthenticatedHistoricRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field-capture': {
      id: '/_authenticated/field-capture'
      path: '/field-capture'
      fullPath: '/field-capture'
      preLoaderRoute: typeof AuthenticatedFieldCaptureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estimates': {
      id: '/_authenticated/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof AuthenticatedEstimatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/container-builds': {
      id: '/_authenticated/container-builds'
      path: '/container-builds'
      fullPath: '/container-builds'
      preLoaderRoute: typeof AuthenticatedContainerBuildsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concept-studio': {
      id: '/_authenticated/concept-studio'
      path: '/concept-studio'
      fullPath: '/concept-studio'
      preLoaderRoute: typeof AuthenticatedConceptStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/proposal/$token': {
      id: '/portal/proposal/$token'
      path: '/portal/proposal/$token'
      fullPath: '/portal/proposal/$token'
      preLoaderRoute: typeof PortalProposalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/invoice/$token': {
      id: '/portal/invoice/$token'
      path: '/portal/invoice/$token'
      fullPath: '/portal/invoice/$token'
      preLoaderRoute: typeof PortalInvoiceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/client-file/$token': {
      id: '/portal/client-file/$token'
      path: '/portal/client-file/$token'
      fullPath: '/portal/client-file/$token'
      preLoaderRoute: typeof PortalClientFileTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/field-capture/$projectId': {
      id: '/_authenticated/field-capture/$projectId'
      path: '/$projectId'
      fullPath: '/field-capture/$projectId'
      preLoaderRoute: typeof AuthenticatedFieldCaptureProjectIdRouteImport
      parentRoute: typeof AuthenticatedFieldCaptureRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/git-sync': {
      id: '/_authenticated/admin/git-sync'
      path: '/admin/git-sync'
      fullPath: '/admin/git-sync'
      preLoaderRoute: typeof AuthenticatedAdminGitSyncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proposals/$id/pdf': {
      id: '/api/proposals/$id/pdf'
      path: '/api/proposals/$id/pdf'
      fullPath: '/api/proposals/$id/pdf'
      preLoaderRoute: typeof ApiProposalsIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedFieldCaptureRouteChildren {
  AuthenticatedFieldCaptureProjectIdRoute: typeof AuthenticatedFieldCaptureProjectIdRoute
}

const AuthenticatedFieldCaptureRouteChildren: AuthenticatedFieldCaptureRouteChildren =
  {
    AuthenticatedFieldCaptureProjectIdRoute:
      AuthenticatedFieldCaptureProjectIdRoute,
  }

const AuthenticatedFieldCaptureRouteWithChildren =
  AuthenticatedFieldCaptureRoute._addFileChildren(
    AuthenticatedFieldCaptureRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedConceptStudioRoute: typeof AuthenticatedConceptStudioRoute
  AuthenticatedContainerBuildsRoute: typeof AuthenticatedContainerBuildsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstimatesRoute: typeof AuthenticatedEstimatesRoute
  AuthenticatedFieldCaptureRoute: typeof AuthenticatedFieldCaptureRouteWithChildren
  AuthenticatedHistoricRoute: typeof AuthenticatedHistoricRoute
  AuthenticatedHomeBuilderRoute: typeof AuthenticatedHomeBuilderRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedJobCostingRoute: typeof AuthenticatedJobCostingRoute
  AuthenticatedJobManagementRoute: typeof AuthenticatedJobManagementRoute
  AuthenticatedKnowledgeBaseRoute: typeof AuthenticatedKnowledgeBaseRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedProposalsRoute: typeof AuthenticatedProposalsRoute
  AuthenticatedSchemaDiffRoute: typeof AuthenticatedSchemaDiffRoute
  AuthenticatedSepticRoute: typeof AuthenticatedSepticRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedAdminGitSyncRoute: typeof AuthenticatedAdminGitSyncRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedConceptStudioRoute: AuthenticatedConceptStudioRoute,
  AuthenticatedContainerBuildsRoute: AuthenticatedContainerBuildsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstimatesRoute: AuthenticatedEstimatesRoute,
  AuthenticatedFieldCaptureRoute: AuthenticatedFieldCaptureRouteWithChildren,
  AuthenticatedHistoricRoute: AuthenticatedHistoricRoute,
  AuthenticatedHomeBuilderRoute: AuthenticatedHomeBuilderRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedJobCostingRoute: AuthenticatedJobCostingRoute,
  AuthenticatedJobManagementRoute: AuthenticatedJobManagementRoute,
  AuthenticatedKnowledgeBaseRoute: AuthenticatedKnowledgeBaseRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedProposalsRoute: AuthenticatedProposalsRoute,
  AuthenticatedSchemaDiffRoute: AuthenticatedSchemaDiffRoute,
  AuthenticatedSepticRoute: AuthenticatedSepticRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedAdminGitSyncRoute: AuthenticatedAdminGitSyncRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EmailHelpRoute: EmailHelpRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiConceptImageRoute: ApiConceptImageRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  PortalClientFileTokenRoute: PortalClientFileTokenRoute,
  PortalInvoiceTokenRoute: PortalInvoiceTokenRoute,
  PortalProposalTokenRoute: PortalProposalTokenRoute,
  ApiProposalsIdPdfRoute: ApiProposalsIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
